Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
AllowedHosts: '*'

Jwt:
  Audience: TestAudience
  Key: e444dff1ba68a27e327484b63b7da2c32a32fc7a52a4a0587fcb10dbfdac1b44
  RefreshTokenExpirationTimeMinutes: 1440
  TokenExpirationTimeMinutes: 5
  Issuer: Test
  RefreshTokenTTLDays: 7

#TODO : Implement IMAP
EmailSettings:
  Server: smtp.gmail.com
  Port: 587
  EnableSsl: true
  Email: nazarovruslan04@gmail.com
  Password: zanb axss upsa gvrk


Cache: 
  DefaultDurationMinutes: 5
